config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  devise_for :users, controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations' }
  get 'clubs/clubadmin', to: "clubs#clubadmin"
  resources :clubs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
    has_one :club_profile
    accepts_nested_attributes_for :club_profile
end

app/models/club_profile.rb
class ClubProfile < ApplicationRecord
  belongs_to :club
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :confirmable, :recoverable, :rememberable, :validatable
  
    has_one :profile, dependent: :destroy, autosave: true
    accepts_nested_attributes_for :profile
  # after_create :send_admin_mail

    protected
    def password_required?
      confirmed? ? super : false
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/club_profiles_controller.rb
class ClubProfilesController < ApplicationController
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def index
    @clubs = Club.all
  end

  def new
    @club = Club.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @club = Club.create(club_params)
    redirect_to clubs_path
  end

  def show
    @club = Club.find(params[:id])
  end

  def edit
    @club = Club.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @club = Club.find(params[:id])
    if @club.update(club_params)
      redirect_to clubs_path
    else
      render 'edit'
    end
  end

  def destroy
    @club = Club.find(params[:id])
    @club.destroy
    redirect_to clubs_path
  end

  def clubadmin
    
  end

  private

  def club_params
    params.require(:club).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    token = resource.send(:set_reset_password_token)
    edit_password_url(resource, reset_password_token: token)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters
  skip_before_action :require_no_authentication, only: [ :new, :create, :cancel ]
  # GET /resource/sign_up
  def new

    # Override Devise default behaviour and create a profile as well
    build_resource({})
    resource.build_profile
    respond_with self.resource
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u|
      u.permit(:email, :password, :password_confirmation, profile_attributes: :first_name)
    }
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
      :user
    end

    def resource
      @resource ||= User.new
    end

    def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/club_profiles_helper.rb
module ClubProfilesHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clubs/_edit.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Club</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>

<%= form_for @club do |f| %>
  <div class="modal-body">
    <%= f.label "Club name" %>
    <%= f.text_field :name %>
  </div>
  
  <div class="modal-footer">
    <%= f.submit "Create",class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/clubs/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Club</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>

<%= form_for @club do |f| %>
  <div class="modal-body">
    <%= f.label "Club name" %>
    <%= f.text_field :name %>
  </div>
  
  <div class="modal-footer">
    <%= f.submit "Create",class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/clubs/clubadmin.html.erb
<h3>Club Admin </h3>

<% resource.build_profile if resource.profile.nil? %>
<%= form_for(resource, :as => resource_name,
                       :url => registration_path(resource_name)) do |f| %>
    <%= devise_error_messages! %>
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true %>

    <%= f.fields_for :profile do |profile_fields| %>
      <%= profile_fields.label "first name" %>
      <%= profile_fields.text_field :first_name %>
      <%= profile_fields.label "address" %>
      <%= profile_fields.text_field :address %>
      <%= profile_fields.label "city" %>
      <%= profile_fields.text_field :city %>
      <%= profile_fields.label "DOB" %>
      <%= profile_fields.date_field :dob %>
      <%= profile_fields.label "gender" %>
      <%= profile_fields.text_field :gender %>
      <%= profile_fields.label "handicap" %>
      <%= profile_fields.text_field :handicap %>
      <%= profile_fields.label "handicap_certified" %>
      <%= profile_fields.text_field :handicap_certified %>
      <%= profile_fields.label "gender" %>
      <%= profile_fields.text_field :gender %>
    <% end %>

      <%= f.submit %>

<% end %>


t.decimal "handicap", precision: 4, scale: 2
t.boolean "handicap_certified"
t.boolean "is_professional"
t.string "last_name"
t.string "licence_number"
t.string "phone_number"
t.string "role"
t.string "state"

app/views/clubs/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'edit') %>");
$("#modal-window").modal();

app/views/clubs/index.html.erb
<style type="text/css">
  .home_links:hover
  {
    color:#fbfbfb!important;
  }
</style>
<div style="background-color:darkgrey">
  <%= link_to 'Home', root_path, class: 'home_links', style: 'color: black' %>
  <%= link_to 'Create Club', new_club_path, {class: 'home_links', remote: true, style: 'color: black', 'data-toggle': "modal", 'data-target': '#modal-window'}  %>
  <%= link_to 'Create Club Admin', clubs_clubadmin_path %>
</div>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>
<br>
<table class="col-6 offset-3 table table-hover table-bordered">
  <tr>
    <th>Club Name</th>
    <th colspan=3>Operation</th>
  </tr>

  <% @clubs.each do |club| %>
    <tr>
      <td><%= club.name %></td>
      <td><%= link_to 'Show', club_path(club) %></td>
      <td><%= link_to 'Edit', edit_club_path(club), {remote: true, 'data-toggle': "modal", 'data-target': '#modal-window'} %></td>
      <td><%= link_to 'Delete', club_path(club), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>

</table>

app/views/clubs/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();

app/views/clubs/show.html.erb
Club Dashboard

<table class="col-6 offset-3 table table-hover table-bordered">
  <tr>
    <th>Club Name</th>
    <th>Operation</th>
  </tr>
  <tr>
    <td><%= @club.name %></td>
    <td><%= link_to 'Edit', edit_club_path(@club), {remote: true, 'data-toggle': "modal", 'data-target': '#modal-window'} %></td>
  </tr>
</table>

app/views/home/index.html.erb
<h1>Super Admin</h1>
<h5><%= current_user.email %> <h5>
<%= link_to 'Club', clubs_path, class: 'btn btn-primary' %>
<%= link_to 'logout', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeeBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>